# Generated by Django 3.1.1 on 2020-10-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Nombre Clave')),
                ('name', models.CharField(max_length=50, verbose_name='Red Social')),
                ('url', models.URLField(blank=True, max_length=50, null=True, verbose_name='Enlace')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'enlace',
                'verbose_name_plural': 'enlaces',
            },
        ),
    ]
